version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  test:
    docker:
      - image: rishabhpoddar/supertokens_core_testing
    steps:
      - checkout
      - run: echo $'\n[mysqld]\ncharacter_set_server=utf8mb4' >> /etc/mysql/mysql.cnf
      - run:
          name: starting mysql
          command: |
            (cd / && ./runMySQL.sh)
            mysql -u root --password=root -e "CREATE DATABASE supertokens;"
      - run:
          name: running tests
          command: (cd .circleci/ && ./doTests.sh)
      - slack/status

workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/